theme: jekyll-theme-cayman
title: Bem-vindo à página sobre Health Data Management da Comsentimento
description: Aqui você vai encontrar tudo sobre os nossos projetos, serviços e tecnologias. Seja você um profissional de TI de uma organização de saúde, um gestor buscando gerar mais valor através de dados, uma startup a procura de dados ou simplesmente um entusiasta da área de ciência de dados, você veio ao local certo.
